#!/usr/bin/env sh

source .env

docker run -p 5432:5432 \
           -e POSTGRES_USER=${POSTGRES_USER} \
           -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
           -e POSTGRES_DB=border_waiting_area \
           -v border-waiting-area-postgres:/var/lib/postgresql/data \
           --name border-waiting-area-postgres \
           -d postgres:15.1-alpine
